-- Create database and user
CREATE DATABASE IF NOT EXISTS crate_dev;
CREATE USER IF NOT EXISTS dev WITH ENCRYPTED PASSWORD 'dev123';
GRANT ALL PRIVILEGES ON DATABASE crate_dev TO dev;
GRANT ALL PRIVILEGES ON SCHEMA public TO dev;

-- Enable required extensions
\c crate_dev;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- Set default permissions
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO dev;